name: Set up Java

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3.1.1
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Check Java version
      run: java -version
